# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-25 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copyright',
            field=models.NullBooleanField(),
        ),
    ]
