# Generated by Django 2.2.13 on 2021-03-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_copyright'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Person',
        ),
        migrations.AddField(
            model_name='book',
            name='translators',
            field=models.ManyToManyField(related_name='books_translated', to='books.Person'),
        ),
    ]
