# Generated by Django 4.2.24 on 2025-10-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='editors',
            field=models.ManyToManyField(related_name='books_edited', to='books.person'),
        ),
    ]
