# Generated by Django 2.2.27 on 2022-03-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_copyright'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='gutenberg_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
