# Generated by Django 4.2.28 on 2026-03-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_person_gutenberg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='related_books',
            field=models.TextField(blank=True, default=''),
        ),
    ]
